[package]
name = "dirty_mike_derive"
version = "0.1.0"
edition = "2024"
description = "Quick and dirty self-instrumentation for Rust"
license = "Unlicense"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
hex = "0.4.3"

[dev-dependencies]
dirty_mike = { version = "0.1", path = "../dirty_mike" }
dirty_mike_core = { version = "0.1", path = "../dirty_mike_core" }
trybuild = "1"
perf-event2 = "0.7.4"
